version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: 'vega'
  - package-ecosystem: bundler
    directory: '/docs'
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
