version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "23:00"
    timezone: PST8PDT
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.3
    - 2.38.5
    - 2.39.0
    - 2.40.0
    - 2.41.2
    - 2.42.2
    - 2.43.1
    - 2.45.1
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.23.0
    - 7.24.0
  - dependency-name: ajv
    versions:
    - 7.1.0
    - 7.1.1
    - 7.2.1
    - 8.0.1
    - 8.1.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: "@types/node"
    versions:
    - 14.14.37
  - dependency-name: dtslint
    versions:
    - 4.0.8
  - dependency-name: jsdom
    versions:
    - 16.5.2
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
  - dependency-name: ajv-formats
    versions:
    - 1.6.0
  - dependency-name: d3-array
    versions:
    - 2.11.0
    - 2.12.0
    - 2.12.1
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.2.0
  - dependency-name: canvas
    versions:
    - 2.7.0
  - dependency-name: tape
    versions:
    - 5.2.0
    - 5.2.1
    - 5.2.2
  - dependency-name: terser
    versions:
    - 5.6.0
  - dependency-name: "@rollup/plugin-babel"
    versions:
    - 5.3.0
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.13.10
- package-ecosystem: bundler
  directory: "/docs"
  schedule:
    interval: daily
    time: "23:00"
    timezone: PST8PDT
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "23:00"
    timezone: PST8PDT
  open-pull-requests-limit: 10
