export default {
  axisMinExtent: 0,
  axisMaxExtent: 200,
  axisDomainWidth: 1,
  axisDomainColor: '#000',
  axisGridWidth: 1,
  axisGridColor: '#ddd',
  axisTickPadding: 2,
  axisTickSize: 5,
  axisTickWidth: 1,
  axisTickColor: '#000',
  axisTickLabelColor: '#000',
  axisTickLabelFont: 'sans-serif',
  axisTickLabelFontSize: 10,
  axisTitlePadding: 2,
  axisTitleColor: '#000',
  axisTitleFont: 'sans-serif',
  axisTitleFontSize: 11,
  axisTitleFontWeight: 'bold'
};
