export {default as bin} from './src/bin';
export {default as bootstrapCI} from './src/bootstrapCI';
export {default as quartiles} from './src/quartiles';
export {random, setRandom} from './src/random';
export {default as randomLCG} from './src/lcg';
export {default as randomInteger} from './src/integer';
export {default as randomKDE} from './src/kde';
export {default as randomMixture} from './src/mixture';
export {default as randomNormal} from './src/normal';
export {default as randomUniform} from './src/uniform';
